const mockHistory = [
  'This is some text',
  'This is some more text',
  'This is another text',
  'This is some text',
  'This is some more text',
  'This is another text',
  'This is some text',
  'This is some more text',
  'This is another text',
  'This is some text',
  'This is some more text',
  'This is another text',
  'This is some text',
  'This is some more text',
  'This is another text',
  'This is some text',
  'This is some more text',
  'This is another text',
  'This is some text',
  'This is some more text',
  'This is another text',
  'This is some text',
  'This is some more text',
  'This is another text',
  'This is some text',
  'This is some more text',
  'This is another text',
  'This is some text',
  'This is some more text',
  'This is another text',
  'This is some text',
  'This is some more text',
  'This is another text',
  'This is some text',
  'This is some more text',
  'This is another text',
];
